/* The following code was generated by JFlex 1.6.0 */

/*
  Pascal language lexer specification
*/
   
/* --------------------------Codigo do usuario------------------------ */
   
import java_cup.runtime.*;
      

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.0
 * from the specification file <tt>C:/Users/Win 7/Pascal_compiler/compilador_pascal/pascal.flex</tt>
 */
class PascalLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\4\1\3\1\0\1\4\1\2\22\0\1\4\6\0\1\1"+
    "\1\10\1\12\1\11\1\54\1\47\1\53\1\7\1\56\12\6\1\45"+
    "\1\44\1\52\1\46\1\50\2\0\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\5\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\5\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\5\1\51\1\0\1\55\1\57\1\5\1\0\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\5\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\5\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\5\1\13\1\0\1\14\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uff92\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\2\1\2\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\2\11\24\3\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\0"+
    "\1\26\1\0\1\27\1\0\1\30\1\0\10\3\1\31"+
    "\10\3\1\32\1\3\1\33\4\3\1\34\1\35\6\3"+
    "\1\36\10\3\1\37\1\40\1\41\1\42\1\43\1\0"+
    "\1\44\6\3\1\45\2\3\1\46\3\3\1\47\5\3"+
    "\1\50\1\51\1\52\5\3\1\53\7\3\1\54\2\3"+
    "\1\55\1\0\3\3\1\56\1\57\2\3\1\60\2\3"+
    "\1\61\2\3\1\62\6\3\1\63\3\3\1\64\1\65"+
    "\1\66\1\67\1\3\1\70\1\3\1\71\1\72\1\73"+
    "\1\3\1\74\2\3\1\75\5\3\1\76\6\3\1\77"+
    "\1\100\1\3\1\101\6\3\1\102\2\3\1\103\1\104"+
    "\1\105\1\106\1\3\1\107\2\3\1\110\2\3\1\111"+
    "\1\112\1\113\4\3\1\114\1\115\4\3\1\116";

  private static int [] zzUnpackAction() {
    int [] result = new int[229];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\140\0\220\0\60\0\300\0\360\0\u0120"+
    "\0\u0150\0\u0180\0\60\0\u01b0\0\60\0\u01e0\0\u0210\0\u0240"+
    "\0\u0270\0\u02a0\0\u02d0\0\u0300\0\u0330\0\u0360\0\u0390\0\u03c0"+
    "\0\u03f0\0\u0420\0\u0450\0\u0480\0\u04b0\0\u04e0\0\u0510\0\u0540"+
    "\0\u0570\0\60\0\u05a0\0\60\0\60\0\u05d0\0\60\0\u0600"+
    "\0\u0630\0\60\0\60\0\60\0\60\0\140\0\u0660\0\u0690"+
    "\0\60\0\u06c0\0\60\0\u06f0\0\u0720\0\u0750\0\u0780\0\u07b0"+
    "\0\u07e0\0\u0810\0\u0840\0\u0870\0\u08a0\0\u08d0\0\u0900\0\u0930"+
    "\0\u0960\0\u0990\0\u09c0\0\u09f0\0\u0a20\0\300\0\u0a50\0\u0a80"+
    "\0\u0ab0\0\u0ae0\0\u0b10\0\u0b40\0\300\0\300\0\u0b70\0\u0ba0"+
    "\0\u0bd0\0\u0c00\0\u0c30\0\u0c60\0\300\0\u0c90\0\u0cc0\0\u0cf0"+
    "\0\u0d20\0\u0d50\0\u0d80\0\u0db0\0\u0de0\0\60\0\60\0\60"+
    "\0\60\0\u0690\0\u0e10\0\300\0\u0e40\0\u0e70\0\u0ea0\0\u0ed0"+
    "\0\u0f00\0\u0f30\0\300\0\u0f60\0\u0f90\0\300\0\u0fc0\0\u0ff0"+
    "\0\u1020\0\u1050\0\u1080\0\u10b0\0\u10e0\0\u1110\0\u1140\0\300"+
    "\0\300\0\300\0\u1170\0\u11a0\0\u11d0\0\u1200\0\u1230\0\300"+
    "\0\u1260\0\u1290\0\u12c0\0\u12f0\0\u1320\0\u1350\0\u1380\0\300"+
    "\0\u13b0\0\u13e0\0\300\0\u1410\0\u1440\0\u1470\0\u14a0\0\300"+
    "\0\300\0\u14d0\0\u1500\0\300\0\u1530\0\u1560\0\300\0\u1590"+
    "\0\u15c0\0\300\0\u15f0\0\u1620\0\u1650\0\u1680\0\u16b0\0\u16e0"+
    "\0\300\0\u1710\0\u1740\0\u1770\0\300\0\300\0\300\0\300"+
    "\0\u17a0\0\300\0\u17d0\0\300\0\300\0\300\0\u1800\0\300"+
    "\0\u1830\0\u1860\0\300\0\u1890\0\u18c0\0\u18f0\0\u1920\0\u1950"+
    "\0\300\0\u1980\0\u19b0\0\u19e0\0\u1a10\0\u1a40\0\u1a70\0\300"+
    "\0\300\0\u1aa0\0\300\0\u1ad0\0\u1b00\0\u1b30\0\u1b60\0\u1b90"+
    "\0\u1bc0\0\300\0\u1bf0\0\u1c20\0\300\0\300\0\300\0\300"+
    "\0\u1c50\0\300\0\u1c80\0\u1cb0\0\300\0\u1ce0\0\u1d10\0\300"+
    "\0\300\0\300\0\u1d40\0\u1d70\0\u1da0\0\u1dd0\0\300\0\300"+
    "\0\u1e00\0\u1e30\0\u1e60\0\u1e90\0\300";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[229];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\2\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\6\1\25\1\6\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\6\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\1\53\1\54\1\55\60\0"+
    "\1\56\1\57\56\56\3\0\1\5\61\0\2\6\6\0"+
    "\27\6\22\0\1\7\1\60\57\0\1\61\61\0\1\62"+
    "\57\0\1\63\46\0\11\64\1\0\46\64\5\0\2\6"+
    "\6\0\14\6\1\65\2\6\1\66\7\6\21\0\2\6"+
    "\6\0\4\6\1\67\10\6\1\70\11\6\21\0\2\6"+
    "\6\0\1\71\6\6\1\72\5\6\1\73\11\6\21\0"+
    "\2\6\6\0\10\6\1\74\4\6\1\75\11\6\21\0"+
    "\2\6\6\0\12\6\1\76\1\6\1\77\10\6\1\100"+
    "\1\6\21\0\2\6\6\0\1\101\7\6\1\102\4\6"+
    "\1\103\4\6\1\104\4\6\21\0\2\6\6\0\15\6"+
    "\1\105\11\6\21\0\2\6\6\0\5\6\1\106\5\6"+
    "\1\107\1\110\12\6\21\0\2\6\6\0\1\111\26\6"+
    "\21\0\2\6\6\0\15\6\1\112\11\6\21\0\2\6"+
    "\6\0\10\6\1\113\4\6\1\114\11\6\21\0\2\6"+
    "\6\0\5\6\1\115\11\6\1\116\7\6\21\0\2\6"+
    "\6\0\1\117\16\6\1\120\7\6\21\0\2\6\6\0"+
    "\4\6\1\121\22\6\21\0\2\6\6\0\4\6\1\122"+
    "\14\6\1\123\5\6\21\0\2\6\6\0\7\6\1\124"+
    "\5\6\1\125\1\6\1\126\6\6\1\127\21\0\2\6"+
    "\6\0\14\6\1\130\3\6\1\131\6\6\21\0\2\6"+
    "\6\0\1\132\26\6\21\0\2\6\6\0\7\6\1\133"+
    "\1\134\16\6\21\0\2\6\6\0\15\6\1\135\11\6"+
    "\62\0\1\136\57\0\1\137\57\0\1\140\1\0\1\141"+
    "\57\0\1\55\10\0\1\56\64\0\1\142\51\0\11\143"+
    "\1\0\46\143\14\64\1\15\43\64\5\0\2\6\6\0"+
    "\3\6\1\144\23\6\21\0\2\6\6\0\17\6\1\145"+
    "\7\6\21\0\2\6\6\0\6\6\1\146\20\6\21\0"+
    "\2\6\6\0\15\6\1\147\11\6\21\0\2\6\6\0"+
    "\20\6\1\150\6\6\21\0\2\6\6\0\1\151\26\6"+
    "\21\0\2\6\6\0\14\6\1\152\12\6\21\0\2\6"+
    "\6\0\23\6\1\153\3\6\21\0\2\6\6\0\24\6"+
    "\1\154\2\6\21\0\2\6\6\0\20\6\1\155\6\6"+
    "\21\0\2\6\6\0\3\6\1\156\23\6\21\0\2\6"+
    "\6\0\21\6\1\157\5\6\21\0\2\6\6\0\12\6"+
    "\1\160\14\6\21\0\2\6\6\0\12\6\1\161\14\6"+
    "\21\0\2\6\6\0\17\6\1\162\7\6\21\0\2\6"+
    "\6\0\14\6\1\163\12\6\21\0\2\6\6\0\21\6"+
    "\1\164\5\6\21\0\2\6\6\0\16\6\1\165\10\6"+
    "\21\0\2\6\6\0\21\6\1\166\5\6\21\0\2\6"+
    "\6\0\1\6\1\167\25\6\21\0\2\6\6\0\3\6"+
    "\1\170\23\6\21\0\2\6\6\0\12\6\1\171\14\6"+
    "\21\0\2\6\6\0\21\6\1\172\5\6\21\0\2\6"+
    "\6\0\2\6\1\173\24\6\21\0\2\6\6\0\15\6"+
    "\1\174\11\6\21\0\2\6\6\0\1\175\1\6\1\176"+
    "\13\6\1\177\10\6\21\0\2\6\6\0\21\6\1\200"+
    "\5\6\21\0\2\6\6\0\17\6\1\201\7\6\21\0"+
    "\2\6\6\0\4\6\1\202\22\6\21\0\2\6\6\0"+
    "\22\6\1\203\4\6\21\0\2\6\6\0\16\6\1\204"+
    "\10\6\21\0\2\6\6\0\10\6\1\205\10\6\1\206"+
    "\5\6\21\0\2\6\6\0\4\6\1\207\22\6\21\0"+
    "\2\6\6\0\17\6\1\210\7\6\21\0\2\6\6\0"+
    "\10\6\1\211\16\6\21\0\2\6\6\0\21\6\1\212"+
    "\5\6\21\0\2\6\6\0\17\6\1\213\7\6\14\0"+
    "\11\143\1\214\46\143\5\0\2\6\6\0\1\215\26\6"+
    "\21\0\2\6\6\0\10\6\1\216\16\6\21\0\2\6"+
    "\6\0\12\6\1\217\14\6\21\0\2\6\6\0\4\6"+
    "\1\220\22\6\21\0\2\6\6\0\17\6\1\221\7\6"+
    "\21\0\2\6\6\0\20\6\1\222\6\6\21\0\2\6"+
    "\6\0\14\6\1\223\12\6\21\0\2\6\6\0\4\6"+
    "\1\224\22\6\21\0\2\6\6\0\4\6\1\225\22\6"+
    "\21\0\2\6\6\0\20\6\1\226\6\6\21\0\2\6"+
    "\6\0\4\6\1\227\22\6\21\0\2\6\6\0\24\6"+
    "\1\230\2\6\21\0\2\6\6\0\2\6\1\231\24\6"+
    "\21\0\2\6\6\0\15\6\1\232\11\6\21\0\2\6"+
    "\6\0\12\6\1\233\14\6\21\0\2\6\6\0\4\6"+
    "\1\234\22\6\21\0\2\6\6\0\4\6\1\235\22\6"+
    "\21\0\2\6\6\0\11\6\1\236\15\6\21\0\2\6"+
    "\6\0\2\6\1\237\3\6\1\240\20\6\21\0\2\6"+
    "\6\0\12\6\1\241\14\6\21\0\2\6\6\0\15\6"+
    "\1\242\11\6\21\0\2\6\6\0\4\6\1\243\22\6"+
    "\21\0\2\6\6\0\10\6\1\244\16\6\21\0\2\6"+
    "\6\0\14\6\1\245\12\6\21\0\2\6\6\0\4\6"+
    "\1\246\22\6\21\0\2\6\6\0\4\6\1\247\22\6"+
    "\21\0\2\6\6\0\21\6\1\250\5\6\21\0\2\6"+
    "\6\0\10\6\1\251\16\6\21\0\2\6\6\0\20\6"+
    "\1\252\6\6\21\0\2\6\6\0\12\6\1\253\14\6"+
    "\21\0\2\6\6\0\7\6\1\254\17\6\14\0\11\143"+
    "\1\214\1\15\45\143\5\0\2\6\6\0\26\6\1\255"+
    "\21\0\2\6\6\0\14\6\1\256\12\6\21\0\2\6"+
    "\6\0\4\6\1\257\22\6\21\0\2\6\6\0\21\6"+
    "\1\260\5\6\21\0\2\6\6\0\21\6\1\261\5\6"+
    "\21\0\2\6\6\0\17\6\1\262\7\6\21\0\2\6"+
    "\6\0\4\6\1\263\22\6\21\0\2\6\6\0\1\264"+
    "\26\6\21\0\2\6\6\0\21\6\1\265\5\6\21\0"+
    "\2\6\6\0\4\6\1\266\22\6\21\0\2\6\6\0"+
    "\6\6\1\267\10\6\1\270\7\6\21\0\2\6\6\0"+
    "\12\6\1\271\14\6\21\0\2\6\6\0\4\6\1\272"+
    "\22\6\21\0\2\6\6\0\4\6\1\273\22\6\21\0"+
    "\2\6\6\0\17\6\1\274\7\6\21\0\2\6\6\0"+
    "\17\6\1\275\7\6\21\0\2\6\6\0\1\276\26\6"+
    "\21\0\2\6\6\0\14\6\1\277\12\6\21\0\2\6"+
    "\6\0\12\6\1\300\14\6\21\0\2\6\6\0\4\6"+
    "\1\301\22\6\21\0\2\6\6\0\1\302\26\6\21\0"+
    "\2\6\6\0\15\6\1\303\11\6\21\0\2\6\6\0"+
    "\14\6\1\304\12\6\21\0\2\6\6\0\17\6\1\305"+
    "\7\6\21\0\2\6\6\0\10\6\1\306\16\6\21\0"+
    "\2\6\6\0\13\6\1\307\13\6\21\0\2\6\6\0"+
    "\4\6\1\310\22\6\21\0\2\6\6\0\5\6\1\311"+
    "\21\6\21\0\2\6\6\0\3\6\1\312\23\6\21\0"+
    "\2\6\6\0\3\6\1\313\23\6\21\0\2\6\6\0"+
    "\1\314\26\6\21\0\2\6\6\0\3\6\1\315\23\6"+
    "\21\0\2\6\6\0\21\6\1\316\5\6\21\0\2\6"+
    "\6\0\6\6\1\317\20\6\21\0\2\6\6\0\14\6"+
    "\1\320\12\6\21\0\2\6\6\0\1\321\26\6\21\0"+
    "\2\6\6\0\3\6\1\322\23\6\21\0\2\6\6\0"+
    "\15\6\1\323\11\6\21\0\2\6\6\0\4\6\1\324"+
    "\22\6\21\0\2\6\6\0\17\6\1\325\7\6\21\0"+
    "\2\6\6\0\1\326\26\6\21\0\2\6\6\0\22\6"+
    "\1\327\4\6\21\0\2\6\6\0\13\6\1\330\13\6"+
    "\21\0\2\6\6\0\12\6\1\331\14\6\21\0\2\6"+
    "\6\0\14\6\1\332\12\6\21\0\2\6\6\0\14\6"+
    "\1\333\12\6\21\0\2\6\6\0\2\6\1\334\24\6"+
    "\21\0\2\6\6\0\17\6\1\335\7\6\21\0\2\6"+
    "\6\0\21\6\1\336\5\6\21\0\2\6\6\0\4\6"+
    "\1\337\22\6\21\0\2\6\6\0\4\6\1\340\22\6"+
    "\21\0\2\6\6\0\1\341\26\6\21\0\2\6\6\0"+
    "\21\6\1\342\5\6\21\0\2\6\6\0\10\6\1\343"+
    "\16\6\21\0\2\6\6\0\15\6\1\344\11\6\21\0"+
    "\2\6\6\0\14\6\1\345\12\6\14\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7872];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\5\1\1\11\1\1\1\11"+
    "\24\1\1\11\1\1\2\11\1\1\1\11\2\1\4\11"+
    "\1\0\1\1\1\0\1\11\1\0\1\11\1\0\51\1"+
    "\4\11\1\1\1\0\50\1\1\0\131\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[229];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    /* Cria um novo java_cup.runtime.Symbol com informacoes sobre o token corrente. 
    Nesse caso o token nao possui valor. */
    
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    
    /* Cria um new java_cup.runtime.Symbol com informacoes sobre
       o token corrente, o token possui um valor*/
       
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }
    
    public String current_lexeme(){
    	int l = yyline+1;
    	int c = yycolumn+1;
    	return " (line: "+l+" , column: "+c+" , lexeme: '"+yytext()+"')";
  	}
  	
  	public int current_line() {
  		return yyline+1;
  	}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  PascalLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 206) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;           
    int totalRead = 0;
    while (totalRead < requested) {
      int numRead = zzReader.read(zzBuffer, zzEndRead + totalRead, requested - totalRead);
      if (numRead == -1) {
        break;
      }
      totalRead += numRead;
    }

    if (totalRead > 0) {
      zzEndRead += totalRead;
      if (totalRead == requested) { /* possibly more input available */
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      return false;
    }

    // totalRead = 0: End of stream
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { throw new Error("Illegal character <"+yytext()+">");
          }
        case 79: break;
        case 2: 
          { /* faz nada */
          }
        case 80: break;
        case 3: 
          { return symbol(sym.IDENTIFIER, yytext());
          }
        case 81: break;
        case 4: 
          { return symbol(sym.DIGSEQ, yytext());
          }
        case 82: break;
        case 5: 
          { return symbol(sym.DOT);
          }
        case 83: break;
        case 6: 
          { return symbol(sym.LPAREN);
          }
        case 84: break;
        case 7: 
          { return symbol(sym.STAR, yytext());
          }
        case 85: break;
        case 8: 
          { return symbol(sym.RPAREN);
          }
        case 86: break;
        case 9: 
          { 
          }
        case 87: break;
        case 10: 
          { return symbol(sym.SEMICOLON);
          }
        case 88: break;
        case 11: 
          { return symbol(sym.COLON);
          }
        case 89: break;
        case 12: 
          { return symbol(sym.EQUAL);
          }
        case 90: break;
        case 13: 
          { return symbol(sym.COMMA);
          }
        case 91: break;
        case 14: 
          { return symbol(sym.GT);
          }
        case 92: break;
        case 15: 
          { return symbol(sym.LBRAC);
          }
        case 93: break;
        case 16: 
          { return symbol(sym.LT);
          }
        case 94: break;
        case 17: 
          { return symbol(sym.MINUS, yytext());
          }
        case 95: break;
        case 18: 
          { return symbol(sym.PLUS, yytext());
          }
        case 96: break;
        case 19: 
          { return symbol(sym.RBRAC);
          }
        case 97: break;
        case 20: 
          { return symbol(sym.SLASH, yytext());
          }
        case 98: break;
        case 21: 
          { return symbol(sym.UPARROW);
          }
        case 99: break;
        case 22: 
          { return symbol(sym.CHARACTER_STRING, yytext());
          }
        case 100: break;
        case 23: 
          { return symbol(sym.DOTDOT);
          }
        case 101: break;
        case 24: 
          { return symbol(sym.STARSTAR);
          }
        case 102: break;
        case 25: 
          { return symbol(sym.DO);
          }
        case 103: break;
        case 26: 
          { return symbol(sym.IF);
          }
        case 104: break;
        case 27: 
          { return symbol(sym.IN);
          }
        case 105: break;
        case 28: 
          { return symbol(sym.OF);
          }
        case 106: break;
        case 29: 
          { return symbol(sym.OR, yytext());
          }
        case 107: break;
        case 30: 
          { return symbol(sym.TO);
          }
        case 108: break;
        case 31: 
          { return symbol(sym.ASSIGNMENT);
          }
        case 109: break;
        case 32: 
          { return symbol(sym.GE);
          }
        case 110: break;
        case 33: 
          { return symbol(sym.LE);
          }
        case 111: break;
        case 34: 
          { return symbol(sym.NOTEQUAL);
          }
        case 112: break;
        case 35: 
          { return symbol(sym.REALNUMBER, yytext());
          }
        case 113: break;
        case 36: 
          { return symbol(sym.AND, yytext());
          }
        case 114: break;
        case 37: 
          { return symbol(sym.DIV, yytext());
          }
        case 115: break;
        case 38: 
          { return symbol(sym.END);
          }
        case 116: break;
        case 39: 
          { return symbol(sym.FOR);
          }
        case 117: break;
        case 40: 
          { return symbol(sym.MOD, yytext());
          }
        case 118: break;
        case 41: 
          { return symbol(sym.NIL);
          }
        case 119: break;
        case 42: 
          { return symbol(sym.NOT, yytext());
          }
        case 120: break;
        case 43: 
          { return symbol(sym.SET);
          }
        case 121: break;
        case 44: 
          { return symbol(sym.VAR);
          }
        case 122: break;
        case 45: 
          { return symbol(sym.XOR);
          }
        case 123: break;
        case 46: 
          { return symbol(sym.CASE);
          }
        case 124: break;
        case 47: 
          { return symbol(sym.CHAR);
          }
        case 125: break;
        case 48: 
          { return symbol(sym.ELSE);
          }
        case 126: break;
        case 49: 
          { return symbol(sym.FILE);
          }
        case 127: break;
        case 50: 
          { return symbol(sym.GOTO);
          }
        case 128: break;
        case 51: 
          { return symbol(sym.REAL);
          }
        case 129: break;
        case 52: 
          { return symbol(sym.THEN);
          }
        case 130: break;
        case 53: 
          { return symbol(sym.TRUE);
          }
        case 131: break;
        case 54: 
          { return symbol(sym.TYPE);
          }
        case 132: break;
        case 55: 
          { return symbol(sym.UNIT);
          }
        case 133: break;
        case 56: 
          { return symbol(sym.USES);
          }
        case 134: break;
        case 57: 
          { return symbol(sym.WITH);
          }
        case 135: break;
        case 58: 
          { return symbol(sym.ARRAY);
          }
        case 136: break;
        case 59: 
          { return symbol(sym.BEGIN);
          }
        case 137: break;
        case 60: 
          { return symbol(sym.CONST);
          }
        case 138: break;
        case 61: 
          { return symbol(sym.FALSE);
          }
        case 139: break;
        case 62: 
          { return symbol(sym.LABEL);
          }
        case 140: break;
        case 63: 
          { return symbol(sym.UNTIL);
          }
        case 141: break;
        case 64: 
          { return symbol(sym.WHILE);
          }
        case 142: break;
        case 65: 
          { return symbol(sym.DOWNTO);
          }
        case 143: break;
        case 66: 
          { return symbol(sym.PACKED);
          }
        case 144: break;
        case 67: 
          { return symbol(sym.RECORD);
          }
        case 145: break;
        case 68: 
          { return symbol(sym.REPEAT);
          }
        case 146: break;
        case 69: 
          { return symbol(sym.STRING);
          }
        case 147: break;
        case 70: 
          { return symbol(sym.BOOLEAN);
          }
        case 148: break;
        case 71: 
          { return symbol(sym.FORWARD);
          }
        case 149: break;
        case 72: 
          { return symbol(sym.INTEGER);
          }
        case 150: break;
        case 73: 
          { return symbol(sym.PROGRAM);
          }
        case 151: break;
        case 74: 
          { return symbol(sym.EXTERNAL);
          }
        case 152: break;
        case 75: 
          { return symbol(sym.FUNCTION);
          }
        case 153: break;
        case 76: 
          { return symbol(sym.INTERFACE);
          }
        case 154: break;
        case 77: 
          { return symbol(sym.PROCEDURE);
          }
        case 155: break;
        case 78: 
          { return symbol(sym.IMPLEMENTATION);
          }
        case 156: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
