
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Aug 25 22:59:10 GMT-03:00 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENTIFIER = 51;
  public static final int CHARACTER_STRING = 52;
  public static final int REAL = 75;
  public static final int GT = 60;
  public static final int PACKED = 31;
  public static final int TYPE = 41;
  public static final int STARSTAR = 71;
  public static final int CONST = 5;
  public static final int GE = 59;
  public static final int UNTIL = 43;
  public static final int ASSIGNMENT = 53;
  public static final int COMMA = 55;
  public static final int RPAREN = 70;
  public static final int LT = 64;
  public static final int INTEGER = 73;
  public static final int LPAREN = 63;
  public static final int FALSE = 78;
  public static final int NOT = 7;
  public static final int LE = 62;
  public static final int NIL = 29;
  public static final int ARRAY = 2;
  public static final int VAR = 45;
  public static final int THEN = 39;
  public static final int GOTO = 23;
  public static final int PBEGIN = 66;
  public static final int UPARROW = 72;
  public static final int EXTERNAL = 37;
  public static final int RECORD = 34;
  public static final int MOD = 13;
  public static final int SLASH = 14;
  public static final int TRUE = 77;
  public static final int PLUS = 11;
  public static final int UNIT = 42;
  public static final int WHILE = 46;
  public static final int EQUAL = 58;
  public static final int IMPLEMENTATION = 25;
  public static final int CHAR = 76;
  public static final int INTERFACE = 27;
  public static final int BOOLEAN = 74;
  public static final int DO = 15;
  public static final int DIGSEQ = 56;
  public static final int FOR = 20;
  public static final int STAR = 10;
  public static final int DIV = 12;
  public static final int DOWNTO = 16;
  public static final int ELSE = 17;
  public static final int DOTDOT = 57;
  public static final int DOT = 50;
  public static final int PROCEDURE = 32;
  public static final int EOF = 0;
  public static final int SEMICOLON = 49;
  public static final int FUNCTION = 22;
  public static final int REPEAT = 35;
  public static final int LABEL = 28;
  public static final int MINUS = 9;
  public static final int IN = 26;
  public static final int OR = 8;
  public static final int SET = 36;
  public static final int error = 1;
  public static final int PFILE = 67;
  public static final int IF = 24;
  public static final int RBRAC = 68;
  public static final int OF = 30;
  public static final int END = 18;
  public static final int COLON = 54;
  public static final int FILE = 19;
  public static final int NOTEQUAL = 65;
  public static final int BEGIN = 3;
  public static final int CASE = 4;
  public static final int FORWARD = 21;
  public static final int STRING = 38;
  public static final int LBRAC = 61;
  public static final int PROGRAM = 33;
  public static final int AND = 6;
  public static final int TO = 40;
  public static final int REALNUMBER = 69;
  public static final int WITH = 47;
  public static final int USES = 44;
  public static final int XOR = 48;
}

